addons:
  apt:
    sources:
      - kalakris-cmake
      - debian-sid
    packages:
      - cmake
      - cmake-data
      - debian-archive-keyring
      - qt5-default

language:
  - cpp

script:
  - mkdir build && cd build && cmake .. && make
