dist:
  - trusty
sudo:
  - false
addons:
  apt:
    packages:
      - qt5-default
      - libqt5xmlpatterns5-dev
      - libarchive-dev
      - libsndfile1-dev

language:
  - cpp

script:
  - mkdir build && cd build && cmake .. && make
